config/routes.rb
Rails.application.routes.draw do
  post '/bookings/save', :to => 'bookings#create'
  get '/bookings/user_list', :to => 'bookings#user_list'
  resources :bookings
  resources :airlines
  get '/flights/list', :to => 'flights#list'
  resources :flights
  get '/city_airports/list', :to => 'city_airports#list'
  resources :city_airports  
  get '/popular_destinations/list', :to => 'popular_destinations#list'
  resources :popular_destinations
  get '/trending_places/list', :to => 'trending_places#list'
  resources :trending_places
  resources :app  

end

app/models/city_airport.rb
class CityAirport < ActiveRecord::Base
	has_many :popular_destinations
end

app/controllers/city_airports_controller.rb
class CityAirportsController < ApplicationController
  before_action :set_city_airport, only: [:show, :edit, :update, :destroy]

  def list
    @city_airports = CityAirport.all
    respond_to do |format|
      format.json { render json: @city_airports }
    end  
  end

  # GET /city_airports
  # GET /city_airports.json
  def index
    @city_airports = CityAirport.all
  end

  # GET /city_airports/1
  # GET /city_airports/1.json
  def show
  end

  # GET /city_airports/new
  def new
    @city_airport = CityAirport.new
  end

  # GET /city_airports/1/edit
  def edit
  end

  # POST /city_airports
  # POST /city_airports.json
  def create
    @city_airport = CityAirport.new(city_airport_params)

    respond_to do |format|
      if @city_airport.save
        format.html { redirect_to @city_airport, notice: 'City airport was successfully created.' }
        format.json { render :show, status: :created, location: @city_airport }
      else
        format.html { render :new }
        format.json { render json: @city_airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /city_airports/1
  # PATCH/PUT /city_airports/1.json
  def update
    respond_to do |format|
      if @city_airport.update(city_airport_params)
        format.html { redirect_to @city_airport, notice: 'City airport was successfully updated.' }
        format.json { render :show, status: :ok, location: @city_airport }
      else
        format.html { render :edit }
        format.json { render json: @city_airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /city_airports/1
  # DELETE /city_airports/1.json
  def destroy
    @city_airport.destroy
    respond_to do |format|
      format.html { redirect_to city_airports_url, notice: 'City airport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city_airport
      @city_airport = CityAirport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_airport_params
      params.require(:city_airport).permit(:city, :city_code, :airport, :picture)
    end
end

app/helpers/city_airports_helper.rb
module CityAirportsHelper
end

app/views/city_airports/_form.html.erb
<%= form_for(@city_airport) do |f| %>
  <% if @city_airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city_airport.errors.count, "error") %> prohibited this city_airport from being saved:</h2>

      <ul>
      <% @city_airport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :city_code %><br>
    <%= f.text_field :city_code %>
  </div>
  <div class="field">
    <%= f.label :airport %><br>
    <%= f.text_field :airport %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/city_airports/edit.html.erb
<h1>Editing City Airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @city_airport %> |
<%= link_to 'Back', city_airports_path %>

app/views/city_airports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing City Airports</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>City code</th>
      <th>Airport</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @city_airports.each do |city_airport| %>
      <tr>
        <td><%= city_airport.city %></td>
        <td><%= city_airport.city_code %></td>
        <td><%= city_airport.airport %></td>
        <td><%= city_airport.picture %></td>
        <td><%= link_to 'Show', city_airport %></td>
        <td><%= link_to 'Edit', edit_city_airport_path(city_airport) %></td>
        <td><%= link_to 'Destroy', city_airport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City airport', new_city_airport_path %>

app/views/city_airports/new.html.erb
<h1>New City Airport</h1>

<%= render 'form' %>

<%= link_to 'Back', city_airports_path %>

app/views/city_airports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @city_airport.city %>
</p>

<p>
  <strong>City code:</strong>
  <%= @city_airport.city_code %>
</p>

<p>
  <strong>Airport:</strong>
  <%= @city_airport.airport %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @city_airport.picture %>
</p>

<%= link_to 'Edit', edit_city_airport_path(@city_airport) %> |
<%= link_to 'Back', city_airports_path %>