config/routes.rb
Rails.application.routes.draw do
  post '/bookings/save', :to => 'bookings#create'
  get '/bookings/user_list', :to => 'bookings#user_list'
  resources :bookings
  resources :airlines
  get '/flights/list', :to => 'flights#list'
  resources :flights
  get '/city_airports/list', :to => 'city_airports#list'
  resources :city_airports  
  get '/popular_destinations/list', :to => 'popular_destinations#list'
  resources :popular_destinations
  get '/trending_places/list', :to => 'trending_places#list'
  resources :trending_places
  resources :app  

end

app/models/flight.rb
class Flight < ActiveRecord::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  def list        

    sql_str = ""

    if params[:price] != ""      
      sql_str += " AND CAST(flights.price AS UNSIGNED) <= #{params[:price]}"
    end 
    
    if params[:airline] != ""
      sql_str += " AND flights.airline = '#{params[:airline]}'"
    end

    @flights = Flight.find_by_sql("
      Select * FROM flights 
      inner join airlines 
      on flights.airline = airlines.airline       
      where flights.departure_airport = '#{params[:departure_airport]}'
      and flights.arrival_airport = '#{params[:arrival_airport]}'
      and DATE(flights.departure_time) = '#{params[:departure_time]}' " + sql_str + " 
      order by departure_time, price")
  end  

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:airline, :departure_airport, :arrival_airport, :departure_time, :arrival_time, :flight_status, :rev_departure_time, :rev_arrival_time, :is_delete, :created_at, :price)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :airline %><br>
    <%= f.text_field :airline %>
  </div>
  <div class="field">
    <%= f.label :departure_airport %><br>
    <%= f.text_field :departure_airport %>
  </div>
  <div class="field">
    <%= f.label :arrival_airport %><br>
    <%= f.text_field :arrival_airport %>
  </div>
  <div class="field">
    <%= f.label :departure_time %><br>
    <%= f.datetime_select :departure_time %>
  </div>
  <div class="field">
    <%= f.label :arrival_time %><br>
    <%= f.datetime_select :arrival_time %>
  </div>
  <div class="field">
    <%= f.label :flight_status %><br>
    <%= f.text_field :flight_status %>
  </div>
  <div class="field">
    <%= f.label :rev_departure_time %><br>
    <%= f.datetime_select :rev_departure_time %>
  </div>
  <div class="field">
    <%= f.label :rev_arrival_time %><br>
    <%= f.datetime_select :rev_arrival_time %>
  </div>
  <div class="field">
    <%= f.label :is_delete %><br>
    <%= f.check_box :is_delete %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Airline</th>
      <th>Departure airport</th>
      <th>Arrival airport</th>
      <th>Departure time</th>
      <th>Arrival time</th>
      <th>Flight status</th>
      <th>Rev departure time</th>
      <th>Rev arrival time</th>
      <th>Is delete</th>
      <th>Created at</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.airline %></td>
        <td><%= flight.departure_airport %></td>
        <td><%= flight.arrival_airport %></td>
        <td><%= flight.departure_time %></td>
        <td><%= flight.arrival_time %></td>
        <td><%= flight.flight_status %></td>
        <td><%= flight.rev_departure_time %></td>
        <td><%= flight.rev_arrival_time %></td>
        <td><%= flight.is_delete %></td>
        <td><%= flight.created_at %></td>
        <td><%= flight.price %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/list.html.erb
<%
@@midnight_list = ""
@@morning_list = ""
@@noon_list = ""
@@evening_list = ""
%>

<%
def time_diff(start_time, end_time)
  seconds_diff = (start_time - end_time).to_i.abs
  hours = seconds_diff / 3600
  seconds_diff -= hours * 3600
  minutes = seconds_diff / 60
  seconds_diff -= minutes * 60
  seconds = seconds_diff
  "#{hours.to_s.rjust(2, '0')}:#{minutes.to_s.rjust(2, '0')}:#{seconds.to_s.rjust(2, '0')}"
end

def category(flight_hour)
	if flight_hour >=0 && flight_hour < 6
		return "midnight_flights"
	elsif flight_hour >= 6 && flight_hour < 12
		return "morning_flights"
	elsif flight_hour >= 12 && flight_hour < 18
		return "noon_flights"
	elsif flight_hour >= 18
		return "evening_flights"	
	end	
end	

def htmlString(c, count)

# return "<li style='top : #{count*45}px; font-family: Raleway;'>
# 	<div class = \"trending\">
# 		<p class = \"city_name\" style=\"padding:5px;padding-top:0px;height: 30px;\"><span style=\"float:left\">&#8377; #{c.price}</span><span style=\"float:right\">#{c.airline}</span></p>		
# 		<div class = \"flight_details\" style = \"height: 200px; font-size : 14px;\">
# 			<p>Departute Time<br><b>#{c.departure_time.to_s.at(11..15)}</b></p>
# 			<p>Arrival Time<br><b>#{c.arrival_time.to_s.at(11..15)}</b></p>			
# 			<p>Travel Time<br><b>#{time_diff(c.arrival_time, c.departure_time).at(0..4)}</b></p>
# 			<p>Flight Status<br><b>#{c.flight_status}</b></p>		
# 		</div>
# 		<p><a class = \"city_book\" href = \"#\">Select</a></p>
# 	</div>
# </li>"

return "<li onmousedown = 'moveList(this)' class='flight_item' style='top : #{count*55}px; font-family: Raleway;'>
	<div class = \"trending\">
		<p class = \"city_name\" style=\"padding:5px;padding-top:0px;height: 40px;\"><span id='price' style=\"float:left\">&#8377; #{c.price}</span><span style=\"float:right\"><img src= '#{c.picture}' height = '30px' width = '80px' /></span></p>	
		<div style= 'height = 30px; margin-top:10px; margin-bottom:10px; text-align:center'>		
		</div>
		<hr style='margin-top:0px;margin-bottom : 5px;'>
		<div class = \"flight_details\" style = \"height: 180px; font-size : 14px;\">
		<table style='width:90%;margin-left:10px;margin-right:10px'>
		<tr style='line-height:30px'><td style='float:left'>Departute</td>
		<td style='float:right'>#{c.departure_time.to_s.at(11..15)}</td>
		</tr>
		<tr style='line-height:30px'><td style='float:left'>Arrival</td>
		<td style='float:right'>#{c.arrival_time.to_s.at(11..15)}</td>
		</tr>
		<tr style='line-height:30px'><td style='float:left'>Travel Time</td>
		<td style='float:right'>#{time_diff(c.arrival_time, c.departure_time).at(0..4)}</td>
		</tr>
		<tr style='line-height:30px'><td style='float:left'>Flight Status</td>
		<td style='float:right; color:green'>#{c.flight_status}</td>
		</tr>
		</table>				
		</div>
		<hr style='margin-top:0px;margin-bottom : 5px;'>		
		<p><a class = \"city_book\" style='color:red'>Select</a></p>
		<h1 style='display:none'>#{c.id}</h1>
	</div>
</li>"

end	

%>


<% if @flights.blank? %>

<ul id = "midnight_flights"> </ul>
<ul id = "morning_flights"> </ul>
<ul id = "noon_flights"> </ul>
<ul id = "evening_flights"> </ul>

<%
else
	midnight_count = 0
	morning_count = 0
	noon_count = 0
	evening_count = 0

	@flights.each do |c| 
		cat = category(c.departure_time.to_s.at(11..12).to_i)		
		case cat
			when "midnight_flights"
				@@midnight_list += htmlString(c, midnight_count)
				midnight_count += 1
			when "morning_flights"
				@@morning_list += htmlString(c, morning_count)
				morning_count += 1
			when "noon_flights"
				@@noon_list += htmlString(c, noon_count)
				noon_count += 1
			when "evening_flights"
				@@evening_list += htmlString(c, evening_count)
				evening_count += 1
		end
	end  
%>

<ul id = "midnight_flights">
	<%= @@midnight_list.html_safe %>
</ul>
<ul id = "morning_flights">
	<%= @@morning_list.html_safe %>
</ul>
<ul id = "noon_flights">
	<%= @@noon_list.html_safe %>
</ul>
<ul id = "evening_flights">
	<%= @@evening_list.html_safe %>
</ul>

<% end %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Airline:</strong>
  <%= @flight.airline %>
</p>

<p>
  <strong>Departure airport:</strong>
  <%= @flight.departure_airport %>
</p>

<p>
  <strong>Arrival airport:</strong>
  <%= @flight.arrival_airport %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @flight.departure_time %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @flight.arrival_time %>
</p>

<p>
  <strong>Flight status:</strong>
  <%= @flight.flight_status %>
</p>

<p>
  <strong>Rev departure time:</strong>
  <%= @flight.rev_departure_time %>
</p>

<p>
  <strong>Rev arrival time:</strong>
  <%= @flight.rev_arrival_time %>
</p>

<p>
  <strong>Is delete:</strong>
  <%= @flight.is_delete %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @flight.created_at %>
</p>

<p>
  <strong>Price:</strong>
  <%= @flight.price %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>