config/routes.rb
Rails.application.routes.draw do
  post '/bookings/save', :to => 'bookings#create'
  get '/bookings/user_list', :to => 'bookings#user_list'
  resources :bookings
  resources :airlines
  get '/flights/list', :to => 'flights#list'
  resources :flights
  get '/city_airports/list', :to => 'city_airports#list'
  resources :city_airports  
  get '/popular_destinations/list', :to => 'popular_destinations#list'
  resources :popular_destinations
  get '/trending_places/list', :to => 'trending_places#list'
  resources :trending_places
  resources :app  

end

app/models/airline.rb
class Airline < ActiveRecord::Base
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController
  before_action :set_airline, only: [:show, :edit, :update, :destroy]

  # GET /airlines
  # GET /airlines.json
  def index
    @airlines = Airline.all
  end

  # GET /airlines/1
  # GET /airlines/1.json
  def show
  end

  # GET /airlines/new
  def new
    @airline = Airline.new
  end

  # GET /airlines/1/edit
  def edit
  end

  # POST /airlines
  # POST /airlines.json
  def create
    @airline = Airline.new(airline_params)

    respond_to do |format|
      if @airline.save
        format.html { redirect_to @airline, notice: 'Airline was successfully created.' }
        format.json { render :show, status: :created, location: @airline }
      else
        format.html { render :new }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airlines/1
  # PATCH/PUT /airlines/1.json
  def update
    respond_to do |format|
      if @airline.update(airline_params)
        format.html { redirect_to @airline, notice: 'Airline was successfully updated.' }
        format.json { render :show, status: :ok, location: @airline }
      else
        format.html { render :edit }
        format.json { render json: @airline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airlines/1
  # DELETE /airlines/1.json
  def destroy
    @airline.destroy
    respond_to do |format|
      format.html { redirect_to airlines_url, notice: 'Airline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airline
      @airline = Airline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airline_params
      params.require(:airline).permit(:airline, :picture)
    end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/views/airlines/_form.html.erb
<%= form_for(@airline) do |f| %>
  <% if @airline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airline.errors.count, "error") %> prohibited this airline from being saved:</h2>

      <ul>
      <% @airline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :airline %><br>
    <%= f.text_field :airline %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_area :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airlines/edit.html.erb
<h1>Editing Airline</h1>

<%= render 'form' %>

<%= link_to 'Show', @airline %> |
<%= link_to 'Back', airlines_path %>

app/views/airlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Airlines</h1>

<table>
  <thead>
    <tr>
      <th>Airline</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airlines.each do |airline| %>
      <tr>
        <td><%= airline.airline %></td>
        <td><%= airline.picture %></td>
        <td><%= link_to 'Show', airline %></td>
        <td><%= link_to 'Edit', edit_airline_path(airline) %></td>
        <td><%= link_to 'Destroy', airline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airline', new_airline_path %>

app/views/airlines/new.html.erb
<h1>New Airline</h1>

<%= render 'form' %>

<%= link_to 'Back', airlines_path %>

app/views/airlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Airline:</strong>
  <%= @airline.airline %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @airline.picture %>
</p>

<%= link_to 'Edit', edit_airline_path(@airline) %> |
<%= link_to 'Back', airlines_path %>