config/routes.rb
Rails.application.routes.draw do
  post '/bookings/save', :to => 'bookings#create'
  get '/bookings/user_list', :to => 'bookings#user_list'
  resources :bookings
  resources :airlines
  get '/flights/list', :to => 'flights#list'
  resources :flights
  get '/city_airports/list', :to => 'city_airports#list'
  resources :city_airports  
  get '/popular_destinations/list', :to => 'popular_destinations#list'
  resources :popular_destinations
  get '/trending_places/list', :to => 'trending_places#list'
  resources :trending_places
  resources :app  

end

app/models/trending_place.rb
class TrendingPlace < ActiveRecord::Base
end

app/controllers/trending_places_controller.rb
class TrendingPlacesController < ApplicationController
  before_action :set_trending_place, only: [:show, :edit, :update, :destroy]

  # GET /trending_places/list
  # GET /trending_places/list.json
  def list
    @trending_places = TrendingPlace.all
  end

  # GET /trending_places
  # GET /trending_places.json
  def index
    @trending_places = TrendingPlace.all
  end

  # GET /trending_places/1
  # GET /trending_places/1.json
  def show
  end

  # GET /trending_places/new
  def new
    @trending_place = TrendingPlace.new
  end

  # GET /trending_places/1/edit
  def edit
  end

  # POST /trending_places
  # POST /trending_places.json
  def create
    @trending_place = TrendingPlace.new(trending_place_params)

    respond_to do |format|
      if @trending_place.save
        format.html { redirect_to @trending_place, notice: 'Trending place was successfully created.' }
        format.json { render :show, status: :created, location: @trending_place }
      else
        format.html { render :new }
        format.json { render json: @trending_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trending_places/1
  # PATCH/PUT /trending_places/1.json
  def update
    respond_to do |format|
      if @trending_place.update(trending_place_params)
        format.html { redirect_to @trending_place, notice: 'Trending place was successfully updated.' }
        format.json { render :show, status: :ok, location: @trending_place }
      else
        format.html { render :edit }
        format.json { render json: @trending_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trending_places/1
  # DELETE /trending_places/1.json
  def destroy
    @trending_place.destroy
    respond_to do |format|
      format.html { redirect_to trending_places_url, notice: 'Trending place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trending_place
      @trending_place = TrendingPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trending_place_params
      params.require(:trending_place).permit(:name, :picture, :is_delete, :created_at)
    end
end

app/helpers/trending_places_helper.rb
module TrendingPlacesHelper
end

app/views/trending_places/_form.html.erb
<%= form_for(@trending_place) do |f| %>
  <% if @trending_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trending_place.errors.count, "error") %> prohibited this trending_place from being saved:</h2>

      <ul>
      <% @trending_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :is_delete %><br>
    <%= f.text_field :is_delete %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trending_places/edit.html.erb
<h1>Editing Trending Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @trending_place %> |
<%= link_to 'Back', trending_places_path %>

app/views/trending_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trending Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Is delete</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trending_places.each do |trending_place| %>
      <tr>
        <td><%= trending_place.name %></td>
        <td><%= trending_place.picture %></td>
        <td><%= trending_place.is_delete %></td>
        <td><%= trending_place.created_at %></td>
        <td><%= link_to 'Show', trending_place %></td>
        <td><%= link_to 'Edit', edit_trending_place_path(trending_place) %></td>
        <td><%= link_to 'Destroy', trending_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trending place', new_trending_place_path %>

app/views/trending_places/list.html.erb
<% if @trending_places.blank? %>
<ul id = "trending_places">
</ul>
<% else %>
<ul id = "trending_places">
  <% @trending_places.each do |c| %>
  <li>
    <div class = "trending">
      <p class = "city_name" id = "popular_dest" ><%= c.name %></p>
      <img src = "<%= image_url(c.picture) %>" class = "city_picture" />
      <p><a id = "popular_find_flights" href = "#" onmousedown = "quickSearch(this)">Select</a></p>
    </div>
  </li>  

  <% end %>
</ul>

<% end %>

app/views/trending_places/new.html.erb
<h1>New Trending Place</h1>

<%= render 'form' %>

<%= link_to 'Back', trending_places_path %>

app/views/trending_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trending_place.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @trending_place.picture %>
</p>

<p>
  <strong>Is delete:</strong>
  <%= @trending_place.is_delete %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @trending_place.created_at %>
</p>

<%= link_to 'Edit', edit_trending_place_path(@trending_place) %> |
<%= link_to 'Back', trending_places_path %>